import { db } from "./db";
import { claims, claimNotes } from "@shared/schema";
import { count } from "drizzle-orm";

export async function seedDatabase() {
  const [{ value: claimCount }] = await db.select({ value: count() }).from(claims);
  if (claimCount > 0) {
    console.log(`Database already has ${claimCount} claims, skipping seed.`);
    return;
  }

  console.log("Seeding database with sample claims...");

  const sampleClaims = [
    {
      firstName: "Maria",
      lastName: "Garcia",
      dateOfInjury: "2025-11-15",
      dateSubmitted: "2025-11-16",
      dateEmployerNotified: "2025-11-16",
      workerType: "W2" as const,
      claimType: "Medical Only" as const,
      claimStatus: "Open" as const,
      injuryType: "Fall/Slip/Trip",
      stateOfInjury: "CA",
      shiftType: "Warehouse Associate",
      partnerName: "Venetian Expo Custodial",
      insuredName: "Garuda Labs Inc dba Instawork",
      carrier: "WorkFirst",
      policyYear: "2025",
      policyNumber: "WF-2025-001234",
      tnsSpecialist: "Carlos",
      stage: "active_claim" as const,
      tldr: "Worker slipped on wet floor in warehouse area during morning shift. Reported immediately to supervisor. Sent to urgent care, diagnosed with mild ankle sprain. Currently on modified duty. Expected full recovery within 4-6 weeks.",
      nextSteps: "Follow up with adjuster on medical authorization. Verify modified duty compliance.",
      totalPayments: "4500.00",
      totalOutstanding: "8500.00",
      medicalTotal: "3200.00",
      fnolFiled: true,
      froiFiled: true,
      wageStatementSent: true,
      medicalPanelSent: true,
      mpnDwc7Sent: true,
      paidFullShift: true,
    },
    {
      firstName: "James",
      lastName: "Williams",
      dateOfInjury: "2025-12-02",
      dateSubmitted: "2025-12-02",
      dateEmployerNotified: "2025-12-03",
      workerType: "1099" as const,
      claimType: "Other Than Medical Only" as const,
      claimStatus: "Open" as const,
      injuryType: "Strain: Lifting",
      stateOfInjury: "TX",
      shiftType: "General Labor",
      partnerName: "Phoenix Convention Center",
      insuredName: "Advantage Workforce Services, LLC",
      carrier: "Great American",
      policyYear: "2025",
      policyNumber: "GA-2025-005678",
      tnsSpecialist: "Janeth",
      adjuster: "Sarah Mitchell",
      stage: "litigation" as const,
      litigated: true,
      applicantAttorney: "Law Office of Rodriguez & Partners",
      defenseAttorney: "Smith & Associates Defense Group",
      tldr: "Worker strained lower back while lifting heavy equipment. Initially treated as medical only, but claimant hired attorney after 3 weeks. Attorney demanding significant lost wages and future medical. Case complexity is moderate.",
      nextSteps: "Prepare defense strategy. Review IME report. Schedule mediation.",
      severityAndPrognosis: "Moderate. L4-L5 disc bulge on MRI. Conservative treatment recommended. May need epidural injections.",
      pathway: "1. Defend at Hearing. 2. Nuisance Settlement.",
      pathwaySteps: "Option 1: Strong defense based on pre-existing conditions. Option 2: Settle in $15-25K range to avoid litigation costs.",
      totalPayments: "12000.00",
      totalOutstanding: "35000.00",
      medicalTotal: "8500.00",
      temporaryDisability: true,
      settlementRecommendation: "20000.00",
      settlementAuthority: "30000.00",
      fnolFiled: true,
      froiFiled: true,
      earningsStatementSent: true,
      paidFullShift: true,
    },
    {
      firstName: "Ashley",
      lastName: "Johnson",
      dateOfInjury: "2026-01-10",
      dateSubmitted: "2026-01-10",
      dateEmployerNotified: "2026-01-10",
      workerType: "W2" as const,
      claimType: "Incident Only" as const,
      claimStatus: "Incident Only" as const,
      injuryType: "Contusion",
      stateOfInjury: "GA",
      shiftType: "Event Server",
      partnerName: "Georgia World Congress Center",
      insuredName: "Garuda Labs Inc dba Instawork",
      carrier: "WorkFirst",
      policyYear: "2026",
      policyNumber: "WF-2026-000112",
      tnsSpecialist: "Bob",
      stage: "intake" as const,
      tldr: "Minor bruise from bumping into catering cart. Worker declined medical treatment. Completed full shift. Incident reported per protocol.",
      fnolFiled: false,
      paidFullShift: true,
      billOfRightsSent: true,
      gaWc1FormSent: true,
    },
    {
      firstName: "Robert",
      lastName: "Chen",
      dateOfInjury: "2025-09-20",
      dateSubmitted: "2025-09-21",
      dateEmployerNotified: "2025-09-21",
      workerType: "W2" as const,
      claimType: "Medical Only" as const,
      claimStatus: "Closed" as const,
      injuryType: "Cut/Laceration",
      stateOfInjury: "NV",
      shiftType: "Prep Cook",
      partnerName: "Las Vegas Convention Center",
      insuredName: "Garuda Labs Inc dba Instawork",
      carrier: "WorkFirst",
      policyYear: "2025",
      policyNumber: "WF-2025-003456",
      tnsSpecialist: "Carlos",
      adjuster: "Mike Thompson",
      stage: "closed" as const,
      dateClosed: "2025-11-30",
      tldr: "Worker cut hand while prepping vegetables. Required 6 stitches at urgent care. Healed fully. Returned to regular duty after 2 weeks modified duty. Claim closed with no further issues.",
      totalPayments: "2800.00",
      totalOutstanding: "0",
      medicalTotal: "2800.00",
      fnolFiled: true,
      froiFiled: true,
      wageStatementSent: true,
      medicalPanelSent: true,
      paidFullShift: true,
      mmi: true,
    },
    {
      firstName: "Diana",
      lastName: "Martinez",
      dateOfInjury: "2026-02-05",
      dateSubmitted: "2026-02-05",
      dateEmployerNotified: "2026-02-06",
      workerType: "W2" as const,
      claimType: "Pending" as const,
      claimStatus: "Open" as const,
      injuryType: "Strain: Repetitive movement",
      stateOfInjury: "CA",
      shiftType: "Custodial",
      partnerName: "Venetian Expo Custodial",
      insuredName: "Garuda Labs Inc dba Instawork",
      carrier: "WorkFirst",
      policyYear: "2026",
      policyNumber: "WF-2026-000234",
      tnsSpecialist: "Janeth",
      stage: "intake" as const,
      tldr: "Worker reports wrist pain from repetitive mopping motions. Pain developed over several shifts. Currently awaiting medical evaluation.",
      nextSteps: "Schedule medical evaluation. Complete intake paperwork. Verify shift history.",
      fnolFiled: true,
      paidFullShift: true,
    },
  ];

  const insertedClaims = await db.insert(claims).values(sampleClaims).returning();
  console.log(`Inserted ${insertedClaims.length} sample claims.`);

  const sampleNotes = [
    {
      claimId: insertedClaims[0].id,
      noteType: "update" as const,
      content: "Spoke with adjuster. Medical authorization approved for follow-up with orthopedic specialist. Appointment scheduled for next week.",
      author: "Carlos",
    },
    {
      claimId: insertedClaims[0].id,
      noteType: "action_item_adjuster" as const,
      content: "Send updated wage statement to adjuster by end of week.",
      author: "Carlos",
      targetDate: "2026-03-01",
      completed: false,
    },
    {
      claimId: insertedClaims[1].id,
      noteType: "action_item_legal" as const,
      content: "Review IME report and prepare counter-offer for mediation.",
      author: "Legal Team",
      targetDate: "2026-03-15",
      completed: false,
    },
    {
      claimId: insertedClaims[1].id,
      noteType: "general_note" as const,
      content: "Applicant attorney submitted demand letter requesting $75,000 including lost wages, future medical, and pain/suffering. Our analysis suggests actual exposure is $20-30K range.",
      author: "Legal Team",
    },
    {
      claimId: insertedClaims[1].id,
      noteType: "status_change" as const,
      content: "Claim escalated from active_claim to litigation stage due to attorney involvement.",
      author: "System",
    },
    {
      claimId: insertedClaims[4].id,
      noteType: "update" as const,
      content: "Intake form received. Worker reports pain started 3 days ago but didn't report until today. Need to verify shift dates and hours worked.",
      author: "Janeth",
    },
  ];

  await db.insert(claimNotes).values(sampleNotes);
  console.log(`Inserted ${sampleNotes.length} sample notes.`);
}
